name: Project Digest

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, closed, synchronize]
  issues:
    types: [opened, edited, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate digest
        uses: actions/github-script@v6
        with:
          script: |
            const payload = context.payload;
            const info = {
              event: context.eventName,
              repo: context.repo.repo,
              actor: context.actor,
              ref: context.ref,
              commit: payload.head_commit?.message,
              pr_title: payload.pull_request?.title,
              issue_title: payload.issue?.title,
              url: payload.pull_request?.html_url || payload.issue?.html_url || payload.head_commit?.url
            };
            console.log("=== Project Digest ===");
            console.log(JSON.stringify(info, null, 2));
